import React from "react";

const CodeScrolling = () => {
  return (
    <svg width="100%" height="100%" xmlns="http://www.w3.org/2000/svg">
      <title>Coding animation</title>
      {/* First group */}
      <g id="group-1">
        <g id="line-1">
          <rect
            id="dash-1"
            fill="#e5e5e5"
            x="0"
            y="0"
            width="70"
            height="10"
            rx="5"
          ></rect>
          <rect
            id="dash-2"
            fill="#e5e5e5"
            x="75"
            y="0"
            width="200"
            height="10"
            rx="5"
          ></rect>
        </g>
        <g id="line-2" transform="translate(30, 20)">
          <rect
            id="dash-1"
            fill="#e5e5e5"
            x="0"
            y="0"
            width="50"
            height="10"
            rx="5"
          ></rect>
        </g>
        <g id="line-3" transform="translate(50, 40)">
          <rect
            id="dash-1"
            fill="#e5e5e5"
            x="0"
            y="0"
            width="80"
            height="10"
            rx="5"
          ></rect>
          <rect
            id="dash-2"
            fill="#e5e5e5"
            x="85"
            y="0"
            width="80"
            height="10"
            rx="5"
          ></rect>
        </g>
        <g id="line-4" transform="translate(0, 60)">
          <rect
            id="dash-1"
            fill="#e5e5e5"
            x="0"
            y="0"
            width="30"
            height="10"
            rx="5"
          ></rect>
          <rect
            id="dash-2"
            fill="#e5e5e5"
            x="35"
            y="0"
            width="80"
            height="10"
            rx="5"
          ></rect>
        </g>
        <g id="line-5" transform="translate(50, 80)">
          <rect
            id="dash-1"
            fill="#e5e5e5"
            x="0"
            y="0"
            width="80"
            height="10"
            rx="5"
          ></rect>
          <rect
            id="dash-2"
            fill="#e5e5e5"
            x="85"
            y="0"
            width="80"
            height="10"
            rx="5"
          ></rect>
        </g>
        <g id="line-6" transform="translate(30, 100)">
          <rect
            id="dash-1"
            fill="#e5e5e5"
            x="0"
            y="0"
            width="50"
            height="10"
            rx="5"
          ></rect>
          <rect
            id="dash-2"
            fill="#e5e5e5"
            x="55"
            y="0"
            width="80"
            height="10"
            rx="5"
          ></rect>
        </g>
        <g id="line-7" transform="translate(120, 120)">
          <rect
            id="dash-1"
            fill="#e5e5e5"
            x="0"
            y="0"
            width="80"
            height="10"
            rx="5"
          ></rect>
          <rect
            id="dash-2"
            fill="#e5e5e5"
            x="85"
            y="0"
            width="150"
            height="10"
            rx="5"
          ></rect>
        </g>
        <g id="line-8" transform="translate(60, 140)">
          <rect
            id="dash-1"
            fill="#e5e5e5"
            x="0"
            y="0"
            width="50"
            height="10"
            rx="5"
          ></rect>
          <rect
            id="dash-2"
            fill="#e5e5e5"
            x="55"
            y="0"
            width="115"
            height="10"
            rx="5"
          ></rect>
        </g>
        <g id="line-9" transform="translate(60, 160)">
          <rect
            id="dash-1"
            fill="#e5e5e5"
            x="0"
            y="0"
            width="70"
            height="10"
            rx="5"
          ></rect>
          <rect
            id="dash-2"
            fill="#e5e5e5"
            x="75"
            y="0"
            width="55"
            height="10"
            rx="5"
          ></rect>
        </g>
        <g id="line-10" transform="translate(80, 180)">
          <rect
            id="dash-1"
            fill="#e5e5e5"
            x="0"
            y="0"
            width="80"
            height="10"
            rx="5"
          ></rect>
          <rect
            id="dash-2"
            fill="#e5e5e5"
            x="85"
            y="0"
            width="80"
            height="10"
            rx="5"
          ></rect>
          <rect
            id="dash-3"
            fill="#e5e5e5"
            x="170"
            y="0"
            width="250"
            height="10"
            rx="5"
          ></rect>
        </g>
      </g>
      {/* Second Group */}
      <g id="group-2">
        <g id="line-1" transform="translate(40, 210)">
          <rect
            id="dash-1"
            fill="#e5e5e5"
            x="0"
            y="0"
            width="100"
            height="10"
            rx="5"
          ></rect>
        </g>
        <g id="line-2" transform="translate(40, 230)">
          <rect
            id="dash-1"
            fill="#e5e5e5"
            x="0"
            y="0"
            width="160"
            height="10"
            rx="5"
          ></rect>
          <rect
            id="dash-2"
            fill="#e5e5e5"
            x="165"
            y="0"
            width="80"
            height="10"
            rx="5"
          ></rect>
        </g>
        <g id="line-3" transform="translate(40, 250)">
          <rect
            id="dash-1"
            fill="#e5e5e5"
            x="100"
            y="0"
            width="80"
            height="10"
            rx="5"
          ></rect>
          <rect
            id="dash-2"
            fill="#e5e5e5"
            x="185"
            y="0"
            width="180"
            height="10"
            rx="5"
          ></rect>
        </g>
        <g id="line-4" transform="translate(80, 270)">
          <rect
            id="dash-1"
            fill="#e5e5e5"
            x="0"
            y="0"
            width="40"
            height="10"
            rx="5"
          ></rect>
          <rect
            id="dash-2"
            fill="#e5e5e5"
            x="45"
            y="0"
            width="85"
            height="10"
            rx="5"
          ></rect>
        </g>
        <g id="line-5" transform="translate(80, 290)">
          <rect
            id="dash-1"
            fill="#e5e5e5"
            x="0"
            y="0"
            width="80"
            height="10"
            rx="5"
          ></rect>
          <rect
            id="dash-2"
            fill="#e5e5e5"
            x="85"
            y="0"
            width="85"
            height="10"
            rx="5"
          ></rect>
          <rect
            id="dash-3"
            fill="#e5e5e5"
            x="175"
            y="0"
            width="105"
            height="10"
            rx="5"
          ></rect>
        </g>
        <g id="line-6" transform="translate(80, 310)">
          <rect
            id="dash-1"
            fill="#e5e5e5"
            x="0"
            y="0"
            width="170"
            height="10"
            rx="5"
          ></rect>
          <rect
            id="dash-2"
            fill="#e5e5e5"
            x="175"
            y="0"
            width="175"
            height="10"
            rx="5"
          ></rect>
        </g>
        <g id="line-7" transform="translate(110, 330)">
          <rect
            id="dash-1"
            fill="#e5e5e5"
            x="0"
            y="0"
            width="80"
            height="10"
            rx="5"
          ></rect>
        </g>
        <g id="line-8" transform="translate(50, 350)">
          <rect
            id="dash-1"
            fill="#e5e5e5"
            x="0"
            y="0"
            width="105"
            height="10"
            rx="5"
          ></rect>
        </g>
      </g>
    </svg>
  );
};

export default CodeScrolling;
